name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        id: snyk
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure file is generated
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=snyk-results.json
      - name: Download Snyk Results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-results
          path: snyk-results.json
      - name: Print Snyk Test Status
        run: |
          echo "Snyk Test Status:"
          echo "-----------------"
          echo "Issues Found: ${{ steps.snyk.outputs.issuesFound }}"
          echo "Return Code: $?"
